---

- name: create auth dir
  file:
    path: /etc/mail/authinfo
    state: directory
    mode: 0700
  tags: template-gmail-creds

- name: configure credentials files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ sendmail_templates }}"
  tags: template-gmail-creds

- name: make mail db
  shell: makemap -r hash /etc/mail/authinfo/gmail-auth.db < /etc/mail/authinfo/gmail-auth
  changed_when: false
  tags: gmail-creds

- name: set permissions
  file:
    path: /etc/mail/authinfo/gmail-auth.db
    mode: 0600
  tags: gmail-creds
